### ISSUE TITLE
Servers validation fails with OAS 3.1.0

### ISSUE THREAD

**Issue by acelaya** [DEVizzent/cebe-php-openapi#5]
I used to use `cebe/php-openapi` to validate my OAS spec, and I'm considering moving to this library, as it supports OAS 3.1

The thing is that, if I switch to `"openapi": "3.1.0"` and run `vendor/bin/php-openapi validate docs/oas.json` I get this warning:

```shell
OpenAPI v3.1 schema violations:
- [servers[0].url] Invalid URL format
```

The servers block looks like this:

```json
{
    "servers": [
        {
            "url": "{scheme}://{host}",
            "variables": {
                "scheme": {
                    "default": "https",
                    "enum": ["https", "http"]
                },
                "host": {
                    "default": ""
                }
            }
        }
    ],
}
```

Which is valid according to OAS 3.1 docs: https://spec.openapis.org/oas/v3.1.0#serverObject

The same command above passes as long as `openapi` is set to 3.0.3: `"openapi": "3.0.3"`

**Comment by DEVizzent** [comment]
The previous JsonSchema has no format for the url.
https://github.com/DEVizzent/cebe-php-openapi/blob/master/schemas/openapi-v3.0.json#L147
The current one have format:
https://github.com/DEVizzent/cebe-php-openapi/blob/master/schemas/openapi-v3.1.json#L165

We have 2 ways:
1 - avoid this validation as it did before.
2 - try to replace the variables by the default value. But your example ("{scheme}://{host}" => "https://") will be invalid, you would need to add something to the default value of host.

**Comment by acelaya** [comment]
Would it make sense to validate it only if it does not contain variables?

**Comment by DEVizzent** [comment]
I will take a look to the code. I think the validation it's done by JSON schema lib, so I can't modify logic inside.

**Comment by acelaya** [comment]
I mean, if it was not validated before, removing the `format` prop is always an option. I would not be against that.

**Comment by DEVizzent** [comment]
Hi again @acelaya, 
I think we can remove this validation. So please check the branch I-5_server_definition_fix it's valid for you and I will merge it.

**Comment by acelaya** [comment]
Using that branch I get this error:

```
Fatal error: Uncaught JsonSchema\Exception\JsonDecodingException: JSON syntax is malformed in /app/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriRetriever.php:213
Stack trace:
#0 /app/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriRetriever.php(181): JsonSchema\Uri\UriRetriever->loadSchema('file:///home/sh...')
#1 /app/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(52): JsonSchema\Uri\UriRetriever->retrieve('file:///home/sh...')
#2 /app/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(115): JsonSchema\SchemaStorage->addSchema('file:///home/sh...')
#3 /app/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(138): JsonSchema\SchemaStorage->getSchema('file:///home/sh...')
#4 /app/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(162): JsonSchema\SchemaStorage->resolveRef('file:///home/sh...')
#5 /app/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php(123): JsonSchema\SchemaStorage->resolveRefSchema(Object(stdClass))
#6 /app/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/SchemaConstraint.php(92): JsonSchema\Constraints\Constraint->checkUndefined(Object(stdClass), Object(stdClass), NULL, NULL)
#7 /app/vendor/justinrainbow/json-schema/src/JsonSchema/Validator.php(61): JsonSchema\Constraints\SchemaConstraint->check(Object(stdClass), Object(stdClass))
#8 /app/vendor/devizzent/cebe-php-openapi/bin/php-openapi(145): JsonSchema\Validator->validate(Object(stdClass), Object(stdClass))
#9 /app/vendor/bin/php-openapi(120): include('/app/ve...')
#10 {main}
  thrown in /app/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriRetriever.php on line 213
```

**Comment by DEVizzent** [comment]
@acelaya Sorry I forgot remove a comma in the Json. Try it now, it's fixed.

**Comment by acelaya** [comment]
Oh, I checked the diff, but I didn't notice the extra comma.

With that it works 🙂. I will try to finish the migration of my docs to proper OAS 3.1, and report back if I find anything else.

Thanks!

**Comment by acelaya** [comment]
@DEVizzent any plans to merge that branch?

**Comment by DEVizzent** [comment]
Released

**Comment by acelaya** [comment]
Thank you!
